M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu24.04.1} date 2025-09-25T14:53:37+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-25T14:53:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X66.305Y-57.81
X66.305Y-63.59
M30
