M48
; DRILL file {KiCad 9.0.3-9.0.3-0~ubuntu24.04.1} date 2025-08-08T20:57:37+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-08T20:57:37+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3-9.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X2.6104Y-2.276
X2.6104Y-2.5035
M30
